
memo = {}
memo[1] = "ABC"

def rec(d) {
  if memo.has_key(d):
    return memo[d]
  else:
    res = "A" + rec(d-1) + "B" + rec(d-1) + "C" + rec(d-1)
    memo[d] = res
    return res
}

k, s, t = input().rstrip().split(' ')

response = rec(int(k))
print(response[s-1: t-1])

"""
AAAAAAAAAA
BCBABCCABC
BAABCBABCC
ABCCAABCBA
BCCABCBAAA
BCBABCCABC
BAABCBABCC
ABCCAABCBA
BCCABCCAAA
BCBABCCABC
BAABCBABCC
ABCCAABCBA
BCCABCBAAA
ABCBABCCAB
CBAABCBABC
CABCCAABCBABCCABCBAAABCBABCCABCBAABCBABCCABCCAABCBABCCABCCAAABCBABCCABCBAABCBABCCABCCAABCBABCCABCCAAAABCBABCCABCBAABCBABCCABCCAABCBABCCABCBAAABCBABCCABCBAABCBABCCABCCAABCBABCCABCCAAABCBABCCABCBAABCBABCCABCCAABCBABCCABCBAAAAABCBABCCABCBAABCBABCCABCCAABCBABCCABCBAAABCBABCCABCBAABCBABCCABCCAABCBABCCABCCAAABCBABCCABCBAABCBABCCABCCAABCBABCCABCBAAAABCBABCCABCBAABCBABCCABCCAABCBABCCABCBAAABCBABCCABCBAABCBABCCABCCAABCBABCCABCCAAABCBABCCABCBAABCBABCCABCCAABCBABCCABCCAAAABCBABCCABCBAABCBABCCABCCAABCBABCCABCBAAABCBABCCABCBAABCBABCCABCCAABCBABCCABCCAAABCBABCCABCBAABCBABCCABCCAABCBABCCABCCAAAAABCBABCCABCBAABCBABCCABCCAABCBABCCABCBAAABCBABCCABCBAABCBABCCABCCAABCBABCCABCCAAABCBABCCABCBAABCBABCCABCCAABCBABCCABCBAAAABCBABCCABCBAABCBABCCABCCAABCBABCCA
"""